services:
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"

      CLUSTER_ID: "1030f18e-b994-4502-909c"
      KAFKA_NODE_ID: "1"

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSET_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - kafka_data:/var/lib/kafka/data
    user: "0"
volumes:
  kafka_data: